/**
 * Per-analysis summary derivation (Feature 010, Game Library milestone).
 *
 * The canonical builder for the game-scoped **per-analysis summary** the Game
 * Library row strip and the analysis-result filters consume
 * (features/010-tactical-detection.md "Game Library Integration" + "Data
 * requirements", specs/domain/game-library.md §7). It composes the canonical
 * Feature-009 domain functions over the latest completed analysis's persisted
 * `MoveAnalysis` — `summarizeAnalysis` for the user-side classification counts
 * and `gameAccuracy` (ADR-024) for per-game accuracy — never a second
 * implementation of that math.
 *
 * The detection holder follows the spec's **absent-vs-zero** contract:
 * `missedTacticCount` is `null` (absent) until a detection pass has completed
 * for the analysis and a real `0` only once a completed pass found nothing.
 * When a pass completes, the count is derived from the records' persisted
 * `missedTactic` annotations (`summarizeAnalysis` `userMissedTactics`), which
 * are the canonical source of the completed-pass count; V1 records always
 * reflect the completed pass (re-analysis yields fresh records).
 *
 * Pure, deterministic and framework-free: no React, Dexie or Worker imports;
 * the input `records` and `options` are never mutated.
 */

import type { Color } from 'chessops/types';
import type { MoveAnalysis } from '@/domain/chess';
import { PUZZLE_GENERATOR_VERSION, type PuzzleGenerationState } from '@/domain/puzzle';
import type { DetectionPassState } from '@/domain/tactics';
import { gameAccuracy } from './accuracy';
import type { ClassificationCounts } from './summary';
import { summarizeAnalysis } from './summary';

/** Detection-pass state of an analysis: `'absent'` until Feature 010 schedules a pass. */
export type SummaryDetectionState = DetectionPassState | 'absent';

/** Puzzle-generation state of an analysis: `'absent'` until Feature 011 schedules a pass. */
export type SummaryPuzzleState = PuzzleGenerationState | 'absent';

/**
 * Live two-stage scan progress of a detection pass (plan 013 W3): how many of
 * the pass's Stage-2 candidates have settled (`done`) out of the total
 * generated by Stage 1 (`total`). `done` counts every candidate that reached a
 * definitive verdict (verified, or rejected/failed by a Stage-2 guard);
 * engine-failed and still-pending candidates are not counted. Absent (`null`)
 * on rows whose pass predates this field or has not started Stage 2.
 */
export interface ScanProgress {
  readonly done: number;
  readonly total: number;
}

export interface BuildAnalysisSummaryOptions {
  /**
   * Detection-pass state to record. Defaults to `'absent'` (no pass has been
   * scheduled or run for this analysis). The service passes `'queued'` when an
   * analysis run completes and `'completed'`/`'failed'` when the pass settles.
   */
  readonly detectionState?: SummaryDetectionState;
  /**
   * User missed-tactic count for a completed pass. Optional: when the state is
   * `'completed'` and no number is supplied, the count is derived from the
   * records' persisted `missedTactic` annotations. For any non-`'completed'`
   * state this is ignored and the stored count is `null` — absent is not zero.
   */
  readonly missedTacticCount?: number | null;
  /**
   * Detection version of the completed pass (Feature 010 writes
   * `DETECTION_VERSION`). Only retained for the `'completed'` state; otherwise
   * the stored version is `null`.
   */
  readonly detectionVersion?: number | null;
  /**
   * Live Stage-2 progress of the pass (plan 013 W3): candidates settled over
   * total. Optional — absent rows default to `null` (older passes). Written by
   * the detection service as candidates settle and retained for every state
   * (`queued`/`inProgress` while running or interrupted, `completed`/`failed`
   * once settled) so a resumed pass restores its totals.
   */
  readonly scanProgress?: ScanProgress | null;
  /**
   * Effective Stage-2 verification depth of the pass (Feature 010 W2,
   * ADR-026/ADR-034), recorded as **provenance only**. It is an additive,
   * non-indexed summary field and is explicitly **not** a freshness input: a
   * completed pass stays current while its `detectionVersion` matches the
   * current constant, whatever depth it was produced at. Absent/`null` on rows
   * written before the field existed.
   */
  readonly verificationDepth?: number | null;
  /**
   * Puzzle-generation state of the analysis (Feature 011). Defaults to
   * `'absent'` (no generation pass has been scheduled or run for this
   * analysis). The generation service passes `'queued'` when its pass starts
   * and `'completed'`/`'failed'` when it settles.
   */
  readonly puzzleState?: SummaryPuzzleState;
  /**
   * Puzzle-generation version of the completed pass (Feature 011 writes
   * `PUZZLE_GENERATOR_VERSION`). Only retained for the `'completed'` state
   * (defaults to `PUZZLE_GENERATOR_VERSION`); otherwise the stored version is
   * `null`. A puzzle *count* is never derived here — the Library reads the
   * live row count of the `puzzles` table (absent ≠ zero).
   */
  readonly puzzleGeneratorVersion?: number | null;
  /**
   * Live generation progress (puzzles assembled/written over total). Optional
   * — absent rows default to `null` (older passes). Written by the generation
   * service as rows settle and retained for every state so a resumed pass
   * restores its totals.
   */
  readonly puzzleProgress?: ScanProgress | null;
}

export interface PerAnalysisSummary {
  /**
   * User-side ADR-023 classification counts (one classification per persisted
   * user move).
   */
  readonly classificationCounts: ClassificationCounts;
  /** Total number of the user's moves that carry a persisted analysis. */
  readonly userMoves: number;
  /** Total analyzed plies (user and opponent). */
  readonly totalMoves: number;
  /**
   * ADR-024 per-game accuracy over the user's usable moves, or `null` when no
   * usable user move exists (the strip shows an em-dash, never a zero).
   */
  readonly accuracy: number | null;
  /** Number of user moves included in the accuracy mean (the sample size). */
  readonly accuracyMoves: number;
  /** Detection-pass state for this analysis; `'absent'` until a pass is scheduled. */
  readonly detectionState: SummaryDetectionState;
  /**
   * User missed-tactic count, or `null` until a detection pass has completed
   * for the analysis (absent ≠ zero). A completed pass that found nothing is
   * the value `0`.
   */
  readonly missedTacticCount: number | null;
  /** Detection version of the completed pass; `null` until one completes. */
  readonly detectionVersion: number | null;
  /**
   * Live Stage-2 progress of the pass, or `null` when no Stage-2 progress has
   * been recorded (older rows / a pass not yet past Stage 1). Never used to
   * claim a running scan: the UI shows a progress bar only while the service
   * reports the game as live.
   */
  readonly scanProgress: ScanProgress | null;
  /**
   * Effective Stage-2 verification depth of the pass, or `null` when the row
   * predates the field or the pass recorded none. Provenance only — never a
   * freshness input (a completed pass is current on `detectionVersion` alone).
   */
  readonly verificationDepth: number | null;
  /** Puzzle-generation state for this analysis; `'absent'` until a pass is scheduled. */
  readonly puzzleState: SummaryPuzzleState;
  /**
   * Puzzle-generator version of the completed generation pass, or `null` until
   * one completes (only a `'completed'` pass may carry a version). A puzzle
   * count is never derived here — the Library reads the live `puzzles` row
   * count of the game (absent ≠ zero).
   */
  readonly puzzleGeneratorVersion: number | null;
  /**
   * Live generation progress (puzzles settled over total), or `null` when no
   * progress has been recorded (older rows / a pass not yet started). Never
   * used to claim a running pass: the UI shows progress only while the service
   * reports the game as live.
   */
  readonly puzzleProgress: ScanProgress | null;
}

function detectionHolderFor(
  state: SummaryDetectionState,
  persistedMissedTactics: number,
  explicitCount: number | null | undefined,
  explicitVersion: number | null | undefined,
): { readonly missedTacticCount: number | null; readonly detectionVersion: number | null } {
  if (state !== 'completed') {
    return { missedTacticCount: null, detectionVersion: null };
  }
  return {
    missedTacticCount: typeof explicitCount === 'number' ? explicitCount : persistedMissedTactics,
    detectionVersion: explicitVersion ?? null,
  };
}

/**
 * Puzzle-state holder mirroring `detectionHolderFor`: `puzzleGeneratorVersion`
 * is non-null only for a `'completed'` generation pass. A completed pass runs
 * at the current generator semantics, so the version defaults to
 * `PUZZLE_GENERATOR_VERSION` when the caller does not supply one; `puzzleProgress`
 * is carried like `scanProgress` (for every state) and wired directly in
 * `buildAnalysisSummary`.
 */
function puzzleHolderFor(
  state: SummaryPuzzleState,
  explicitVersion: number | null | undefined,
): { readonly puzzleGeneratorVersion: number | null } {
  if (state !== 'completed') {
    return { puzzleGeneratorVersion: null };
  }
  return { puzzleGeneratorVersion: explicitVersion ?? PUZZLE_GENERATOR_VERSION };
}

/**
 * Build the persisted per-analysis summary for one completed analysis run over
 * its `MoveAnalysis` records (Features 008/009 outputs) and the user's color.
 * `records` are read-only and never mutated.
 */
export function buildAnalysisSummary(
  records: readonly MoveAnalysis[],
  userColor: Color,
  options: BuildAnalysisSummaryOptions = {},
): PerAnalysisSummary {
  const analysis = summarizeAnalysis(records, userColor);
  const accuracy = gameAccuracy(records, userColor);
  const detectionState: SummaryDetectionState = options.detectionState ?? 'absent';
  const holder = detectionHolderFor(
    detectionState,
    analysis.userMissedTactics,
    options.missedTacticCount,
    options.detectionVersion,
  );
  const puzzleState: SummaryPuzzleState = options.puzzleState ?? 'absent';
  const puzzleHolder = puzzleHolderFor(puzzleState, options.puzzleGeneratorVersion);
  return {
    classificationCounts: analysis.user,
    userMoves: analysis.userMoves,
    totalMoves: analysis.totalMoves,
    accuracy: accuracy.accuracy,
    accuracyMoves: accuracy.moves,
    detectionState,
    missedTacticCount: holder.missedTacticCount,
    detectionVersion: holder.detectionVersion,
    scanProgress: options.scanProgress ?? null,
    verificationDepth: options.verificationDepth ?? null,
    puzzleState,
    puzzleProgress: options.puzzleProgress ?? null,
    puzzleGeneratorVersion: puzzleHolder.puzzleGeneratorVersion,
  };
}
