/// <reference types="node" />
import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const stylesDir = join(process.cwd(), 'src/components/chessboard/styles');

function themeCss(name: string): string {
  return readFileSync(join(stylesDir, `board-${name}.css`), 'utf8');
}

describe('board theme CSS assets', () => {
  const themes = ['brown', 'blue', 'green', 'purple', 'wood'];

  it('every board theme ships a light background colour and a dark-square SVG overlay', () => {
    for (const theme of themes) {
      const css = themeCss(theme);
      const bg = css.match(/background-color:\s*(#[0-9a-f]{3,6});/i);
      expect(bg, `${theme}: background-color`).toBeTruthy();
      const uri = css.match(/background-image:\s*url\('data:image\/svg\+xml;base64,([^']+)'\);/);
      expect(uri, `${theme}: data URI`).toBeTruthy();
      const svg = Buffer.from(uri![1]!, 'base64').toString('utf8');
      expect(svg).toContain('<svg');
      expect(svg).toContain('</svg>');
      // The overlay must contain dark-square rects but not the whole board
      // colour (that would render a flat single-colour board).
      const darkRects = (svg.match(/<rect[^>]*fill="#[0-9a-f]{3,6}"/gi) ?? []).length;
      expect(darkRects, `${theme}: dark rect count`).toBe(32);
    }
  });

  it('the theme files are the generated two-tone ones (no corrupt hand-written URI)', () => {
    const files = readdirSync(stylesDir).filter((f) =>
      /^board-(brown|blue|green|purple|wood)\.css$/.test(f),
    );
    expect(files).toHaveLength(5);
    for (const file of files) {
      const css = readFileSync(join(stylesDir, file), 'utf8');
      expect(css).toContain('Generated by');
    }
  });
});
